// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLShortener creates a new instance of MockURLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLShortener {
	mock := &MockURLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLShortener is an autogenerated mock type for the URLShortener type
type MockURLShortener struct {
	mock.Mock
}

type MockURLShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLShortener) EXPECT() *MockURLShortener_Expecter {
	return &MockURLShortener_Expecter{mock: &_m.Mock}
}

// Shorten provides a mock function for the type MockURLShortener
func (_mock *MockURLShortener) Shorten(ctx context.Context, originalURL string, alias string, userEmail string) (string, error) {
	ret := _mock.Called(ctx, originalURL, alias, userEmail)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, originalURL, alias, userEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, originalURL, alias, userEmail)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, originalURL, alias, userEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortener_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockURLShortener_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
//   - alias string
//   - userEmail string
func (_e *MockURLShortener_Expecter) Shorten(ctx interface{}, originalURL interface{}, alias interface{}, userEmail interface{}) *MockURLShortener_Shorten_Call {
	return &MockURLShortener_Shorten_Call{Call: _e.mock.On("Shorten", ctx, originalURL, alias, userEmail)}
}

func (_c *MockURLShortener_Shorten_Call) Run(run func(ctx context.Context, originalURL string, alias string, userEmail string)) *MockURLShortener_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockURLShortener_Shorten_Call) Return(s string, err error) *MockURLShortener_Shorten_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLShortener_Shorten_Call) RunAndReturn(run func(ctx context.Context, originalURL string, alias string, userEmail string) (string, error)) *MockURLShortener_Shorten_Call {
	_c.Call.Return(run)
	return _c
}
