version: 3
tasks:
  start:
    cmds:
      - go run ./cmd/url-shortener/ --config ./config/local.yaml

  migrate:up:
    cmds:
      - go run ./cmd/migrator/ --config ./config/local.yaml --direction up

  migrate:down:
    cmds:
      - go run ./cmd/migrator/ --config ./config/local.yaml --direction down
