// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLDeleter creates a new instance of MockURLDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLDeleter {
	mock := &MockURLDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLDeleter is an autogenerated mock type for the URLDeleter type
type MockURLDeleter struct {
	mock.Mock
}

type MockURLDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLDeleter) EXPECT() *MockURLDeleter_Expecter {
	return &MockURLDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockURLDeleter
func (_mock *MockURLDeleter) Delete(ctx context.Context, alias string, requesterEmail string, requesterID int64) error {
	ret := _mock.Called(ctx, alias, requesterEmail, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(ctx, alias, requesterEmail, requesterID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockURLDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
//   - requesterEmail string
//   - requesterID int64
func (_e *MockURLDeleter_Expecter) Delete(ctx interface{}, alias interface{}, requesterEmail interface{}, requesterID interface{}) *MockURLDeleter_Delete_Call {
	return &MockURLDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, alias, requesterEmail, requesterID)}
}

func (_c *MockURLDeleter_Delete_Call) Run(run func(ctx context.Context, alias string, requesterEmail string, requesterID int64)) *MockURLDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockURLDeleter_Delete_Call) Return(err error) *MockURLDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, alias string, requesterEmail string, requesterID int64) error) *MockURLDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}
